### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jlang7** [ChrisTruncer/Egress-Assess#33]
When running the following command...
Invoke-EgressAssess -client http -IP X.X.X.X -ResolveDNS -Proxy -Datatype ssn -Size 5 -Loops 1 -Report c:\temp\report.txt -Verbose
I get this error...
VERBOSE: Report File = c:\temp\report.txt
Unable to find type [ordered]: make sure that the assembly containing this type is loaded.
At line:1019 char:34
+             $EAreport = [ordered] <<<< @{
    + CategoryInfo          : InvalidOperation: (ordered:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TypeNotFound

**Comment by jlang7** [comment]
It maybe useful to have a way to disable the ping check in the PS script.

**Comment by ChrisTruncer** [comment]
Hm... thanks for reporting this.  I think @rvrsh3ll will probably have to look into this.

**Comment by jlang7** [comment]
Thanks

**Comment by rvrsh3ll** [comment]
Yep, this was coming in the next revision, but i'll make a hotfix now.

**Comment by rvrsh3ll** [comment]
I added the -NoPing switch. FYI -ResolveDNS is only used for ICMP transfers. Your command should look like this "./Egress-Assess.ps1 -ip x.x.x.x -client http -datatype ssn -size 5 -report report.txt -verbose"

Happy egressing! Thanks for the request.

**Comment by ChrisTruncer** [comment]
Closing this out, let us know if this is still an issue!
