### ISSUE TITLE
Identity data type issue...

### ISSUE THREAD

**Issue by jlang7** [ChrisTruncer/Egress-Assess#34]
The following command...
date; IEX (New-Object Net.Webclient).DownloadString('https://raw.githubusercontent.com/ChrisTruncer/Egress-Assess/master/Invoke-EgressAssess.ps1‘); Invoke-EgressAssess -client http -IP x.x.x.x -ResolveDNS -Proxy -Datatype identity -Size 5 -Loops 1 -Verbose; date;

Returns the following results...
Thursday, October 08, 2015 11:38:35 AM
VERBOSE: [*] Testing server connection
VERBOSE: [*] Server is UP on secure.malofsky-schwartz.com.
VERBOSE: [*] HTTP Server Running on secure.malofsky-schwartz.com port 80.
VERBOSE: Uploading  data...

VERBOSE: [*] Transfer complete!
VERBOSE: [*] 0 loops remaining..
VERBOSE: Uploading data..

VERBOSE: [*] Transaction Complete.
VERBOSE: [*] Exiting..
Thursday, October 08, 2015 11:38:38 AM

**Comment by ChrisTruncer** [comment]
Ok, and this puts nothing on the server?  I'll be testing this soon

**Comment by ChrisTruncer** [comment]
Ah, this actually isn't a code problem.  The module for "identity" is actually called names for powershell.  It might help if we change this to match identity.  But for the meantime, just use "names" and you should be good.
