### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by c0d3xpl0it** [ChrisTruncer/Egress-Assess#47]
I am facing the timeout error on Exfiltration using HTTPS. 

**On Server:**
p@kali:~/Egress-Assess$ sudo ./Egress-Assess.py --server https

**On Client :**
PS C:\Users\Egress-Assess-master> Invoke-EgressAssess -client https -datatype cc -Verbose -ip 9.73.2.1
VERBOSE: [*] Testing server connection
VERBOSE: [*] Server is UP on 9.73.2.1.
VERBOSE: [*] Error, tranfer failed with error:
VERBOSE: Exception calling "Connect" with "2" argument(s): "A connection attempt failed because the connected party did not properly respond after a period of
time, or established connection failed because connected host has failed to respond 9.73.2.1:443"
PS C:\Users\Egress-Assess-master>

But when I browse 9.73.2.1:443 using browser, i can see the request. Any help.

**Comment by c0d3xpl0it** [comment]
Any help Chris ?

**Comment by ChrisTruncer** [comment]
Just realized I hadn't reviewed this. Did you get it working?

**Comment by c0d3xpl0it** [comment]
Yes, just used -NOPing flag at client end.
