### ISSUE TITLE
--file not working with smb

### ISSUE THREAD

**Issue by leebaird** [ChrisTruncer/Egress-Assess#51]
- Server
./Egress-Assess.py --server smb

- Client
./Egress-Assess.py --client smb --file /root/secrets.txt --ip 10.0.0.10
##############################################################

smbclient \\\\10.0.0.10\\DATA -N -c "put secrets.txt"
WARNING: The "syslog" option is deprecated
secrets.txt does not exist
[+] File Transmitted!
##############################################################

Notice that the file paths to secrets.txt are different.
Same thing works fine with https.

**Comment by ChrisTruncer** [comment]
should be fixed, thanks!
